### ISSUE TITLE
Angular App Not Building

### ISSUE THREAD

**Issue by Stewartarmbrecht** [Azure-Samples/Serverless-Eventing-Platform-for-Microservices#9]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature  request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 

- Start with a fresh instance and follow the instructions to create all build and release definitions.
- Run all builds and releases in the recommended order.
- After the web app is built and deployed it does not contain the angular app.

### Any log messages given by the failure
> You get a 404 when you try to navigate to the root of the web app.

### Expected/desired behavior
> The resulting web app would be built and hosted in the crwebxxx app.

### OS and Version?
> Azure

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by priyaananthasankar** [comment]
Thanks for reporting this. Will take a look at VSTS. We are providing build and deploy scripts for easy deploy.

**Comment by Stewartarmbrecht** [comment]
Thanks @priyaananthasankar!  I was able to get the solution to build and deploy but I had to change the build file to have these two tasks:

```
# Build Angular App
- task: Npm@1
  name: InstallNpmPackages
  inputs:
    command: install
    workingDir: 'web/src/signalr-web/SignalRMiddleware/EventApp'
    verbose: true

# Build Angular App
- script: npm run dist
  displayName: npm run dist
  workingDirectory: 'web/src/signalr-web/SignalRMiddleware/EventApp'


```
